import {
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'users',
        path: '/users',
        title: 'Users',
        translateKey: 'nav.users',
        icon: 'users',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'sellers',
        path: '/sellers',
        title: 'Sellers',
        translateKey: 'nav.sellers',
        icon: 'sellers',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'categories',
        path: '/categories',
        title: 'Categories',
        translateKey: 'nav.categories',
        icon: 'categories',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'brands',
        path: '/brands',
        title: 'Brands',
        translateKey: 'nav.brands',
        icon: 'brands',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'models',
        path: '/models',
        title: 'Models',
        translateKey: 'nav.models',
        icon: 'models',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },

    {
        key: 'halls',
        path: '/halls',
        title: 'Manage Halls',
        translateKey: 'nav.halls',
        icon: 'halls',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'orders',
        path: '/orders',
        title: 'Orders',
        translateKey: 'nav.orders',
        icon: 'orders',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'fixedPrice',
        path: '/fixed-price',
        title: 'Fixed Price Items',
        translateKey: 'nav.fixedPrice',
        icon: 'fixedPrice',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'liveAuctions',
        path: '',
        title: 'Auctions',
        translateKey: 'nav.collapseMenu.auctions',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'live-auctions',
                path: '/live-auctions',
                title: 'Live Auctions',
                translateKey: 'nav.collapseMenu.liveAuctions',
                icon: 'liveAuctions',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [],
            },
            {
                key: 'duration-auctions',
                path: '/duration-auctions',
                title: 'Duration Auctions',
                translateKey: 'nav.collapseMenu.durationAuctions',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'manageLocation',
        path: '',
        title: 'Manage Location',
        translateKey: 'nav.manageLocation.title',
        icon: 'location',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'regions',
                path: '/locations/regions',
                title: 'Regions',
                translateKey: 'nav.manageLocation.regions',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'disputes',
        path: '/disputes',
        title: 'Disputes',
        translateKey: 'nav.disputes',
        icon: 'disputes',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'languages',
        path: '/languages',
        title: 'Languages',
        translateKey: 'nav.languages',
        icon: 'languages',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    // {
    //     key: 'manageAds',
    //     path: '/manage-ads',
    //     title: 'Manage Ads',
    //     translateKey: 'nav.manageAds',
    //     icon: 'manageAds',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    // {
    //     key: 'payments',
    //     path: '/payments',
    //     title: 'Payments',
    //     translateKey: 'nav.payments',
    //     icon: 'payments',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },

    // {
    //     key: 'support',
    //     path: '/support',
    //     title: 'Support',
    //     translateKey: 'nav.support',
    //     icon: 'support',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },

]

export default navigationConfig
