const ReactQueryKeys = {
  SIGN_IN: "sign-in",
  GET_PROFILE: "get-profile",
  REFRESH_TOKEN: "refresh-token",
  VERIFY_OTP: "verify-otp",
  RESEND_OTP: "resend-otp",
  FORGOT_PASSWORD: "forgot-password",
  CHANGE_PASSWORD: "change-password",
  RESET_PASSWORD: "reset-password",
  LOGOUT: "logout",
  // users
  ALL_USERS: "all-users",
  GET_USER_DETAILS: "details-user",
  // categories
  ALL_CATEGORIES: "all-categories",
  CATEGORY_BY_ID: "category-by-id",
  CATEGORIES_TREE: "categories-tree",
  // brands
  ALL_BRANDS: "all-brands",
  BRAND_BY_ID: "brand-by-id",
  // models
  ALL_MODELS: "all-models",
  MODEL_BY_ID: "model-by-id",
  // languages
  ALL_LANGUAGES: "all-languages",
  LANGUAGE_BY_ID: "language-by-id",
  // sellers
  ALL_SELLERS: "all-sellers",
  GET_SELLER_DETAILS: "seller-details",
  SELLER_DOCUMENTS: "seller-documents",
  // products
  ALL_PRODUCTS: "all-products",
  PRODUCT_BY_ID: "product-by-id",
  // regions
  ALL_REGIONS: "all-regions",
  // cities
  ALL_CITIES: "all-cities",
}
export default ReactQueryKeys